package dev.softwarefactory.run;

/** How a run's tasks are generated; persisted as plain text in the run state. */
public final class RunMode {
    /** Recorded artifacts are replayed; no model is called. */
    public static final String FIXTURE = "fixture";
    /** Tasks are generated by the live model, within the run's call budget. */
    public static final String LIVE = "live";

    private RunMode() {}

    static boolean isKnown(String mode) {
        return FIXTURE.equals(mode) || LIVE.equals(mode);
    }
}
